### ISSUE TITLE
Broken link and broken example, is this project alive??

### ISSUE THREAD

**Issue by GiganteX** [thelinuxlich/artemis_CSharp#101]
The forum link on the Artemis frontpage is broken.

The sample code on the page is broken, for example:
Velocity velocity = e.getComponent<Velocity>();
should be a capital G in GetComponent.

The sample application code StarWarrior is broken, for example:
public class RenderSystem : EntityProcessingSystem<SpatialFormComponent,TransformComponent>

Creating a class like that doesn't work. Not anymore, I'm guessing it's an old design.

So, stuff needs updating.

Might seem like silly nitpicking, but first impressions are important. And if the showcase sample stuff doesn't work as described, it's going to turn people off.

**Comment by thelinuxlich** [comment]
As you can guess from the project activity, we are looking for mantainers.
