### ISSUE TITLE
Port to .NET Standard 2.0

### ISSUE THREAD

**Issue by Thraka** [thelinuxlich/artemis_CSharp#102]
It would be awesome to port this to .NET Standard 2.0. I wish I had the time to do it.

**Comment by thelinuxlich** [comment]
Me too :(

**Comment by tpastor** [comment]
what about removing almost all the extra stuff that we have and its kinda unsupportable anymore ... and just have the core with .net standard 2.0 + unit tests (everything else is removed)

btw, metro, windows phone, xbox, xna .... those stuff does not exist anymore. Lets just have one solution with 2 projects targeting .net std 2.0 version and generating a single dll

comments please, if we reach and an agreement, i can do this.

**Comment by thelinuxlich** [comment]
XNA exists in its spiritual successor only: http://www.monogame.net

**Comment by tpastor** [comment]
Monogame will work with .net std as well, i cant find a good reason to keep
all the different profiles.

btw, migrating to .net std 2.0 is pretty straightforward, i just created a
new solution with the code and compiled everything.... just 3 unit tests
failed :)
Now i just need to fix the test failures, remove all the ifdefs / unused
libs and create the pr.

**Comment by Thraka** [comment]
Is this available in a branch?

**Comment by tpastor** [comment]
ultra simplified -> one solution, 2 projects
all tests ok
tested on visual studio for mac

missing
- remove thousands of ifdefs that are not used ...
- update readme

https://github.com/thelinuxlich/artemis_CSharp/tree/netstandard20

**Comment by tpastor** [comment]
updated the readme with a link to this branch
