### ISSUE TITLE
Incorrect use of GUID as a UniqueId

### ISSUE THREAD

**Issue by Maximusya** [thelinuxlich/artemis_CSharp#70]
`Entity.UniqueId` is generated by `EntityManager` using `System.Guid`:

`BitConverter.ToInt64(Guid.NewGuid().ToByteArray(), 0);`

Guid is 16 byte. We truncate it by half to 8 bytes.
Guid is not guarantied to be unique, all the more so its half.
While internally to Artemis UniqueIds are not actually required to be unique, they might be required to be for Client-Server applications. But Guid implementations might differ on Client and Server - thus cannot be relied on, strictly speaking. For reassurance Entities birth place can be resticted to one side - Server.

Well, creating an Entity with a predefined UniqueId is supported, so workarounds can be used.

**Comment by KellanHiggins** [comment]
Any more thoughts on this. What about changing the Unique ID to just be a 128 bit GUID. Any problems with performance here?

I know this would simplify my networking work on my game. Then I could use this to identify the unique peer connected.

**Comment by thelinuxlich** [comment]
I'm okay with 128bit GUID.

**Comment by KellanHiggins** [comment]
I don't have a great understanding of the performance hit that it could have. Would it be big as it is a dictionary lookup compared to 64 bit?

**Comment by KellanHiggins** [comment]
Any reason this was closed or was no one doing anything to update this? I think this is still an important change we should make.

**Comment by thelinuxlich** [comment]
Maybe what would be nice is a port of this project to C#:

https://github.com/dylang/shortid

And then we could pre-generate these ids for the entity pool

**Comment by captkirk88** [comment]
I would encourage you to check out how Lidgren does random, https://github.com/lidgren/lidgren-network-gen3/blob/master/Lidgren.Network/NetRandomSeed.cs

**Comment by KellanHiggins** [comment]
I am using this as a reference to a database, but I realize I don't really need to produce this in the EntityWorld to be completely unique. I could do this elsewhere and store it on the entity in a component.

I think the most important thing here is to have a unique number associated with an Entity within the EntityWorld instance. So a huge Int 64 is not really needed, unless you want billions of entities that would completely destroy a server.

**Comment by captkirk88** [comment]
If you don't need true uniqueness you could always just assign the ID of the entity as it's index in the pool.  Then when an entity is replaced that entities ID would persist.  This could cause you problems with synchronicity of clients if they have a non-networked entity that is assigned an ID that a networked entity has.  I feel your pain with networking entities.  I had to design my own entity system to be able to get the best performance and had to go with Fody.PropertyChanged to ensure only entity components that had actually been modified were sent over the network, which helped with bandwidth.  I also used Lidgren if that is an option for you, definitely look into it.  Lidgren is unique in that it performs some neat tricks with bit shifting to compress data.

**Comment by KellanHiggins** [comment]
Using Photon Server for the backend, probably too deep in to change to Lidgren. I've been experimenting with byte arrays to get maximum performance at the cost of sustainability and and it seems to be working fine.

As for the Unique IDs, I've been attaching a component to the entities that are controlled by players and just adding a GUID there. Should work fine. I still think we need a better way of creating a Unique ID in an entity world though!
