### ISSUE TITLE
Hierarchy managing

### ISSUE THREAD

**Issue by KingKnecht** [thelinuxlich/artemis_CSharp#82]
Hi,

is it possible to have a component like:

 public class Children : IComponent
    {
        public Children()
        {
            EntityIds = new List<int>();
        }
        public List<int> EntityIds { get; set; }
    }
?

I think, there are situation in the core where objects get cloned. Is this algorithm able to handle lists?
Cheers,
KK

**Comment by KellanHiggins** [comment]
What is the list of EntityIds for? What does it hold?

There are two ways to store Entities. You can store them as a List<int> EntityIds or you can store them as List<Entity> Entities and store the reference to the entity object.

What is your use case?

**Comment by KingKnecht** [comment]
Ops, sorry. I wanted to write List<int>.
I want to store the IDs of entities. I can also store the references of entities, you say? Hmm, I have to think about this option. But good to know.
My use case is that I need a lot of hierarchical organised data. I need to manage parts of a machine. These parts can belong to an assembly, the assembly can also be part of an assembly and so on... 

Thanks!

**Comment by KingKnecht** [comment]
Ah, the editor is eleminating &lt; and &gt;

I mean List&lt;int&gt;

**Comment by KellanHiggins** [comment]
Have you reviewed this article on <a href="http://t-machine.org/index.php/2007/09/03/entity-systems-are-the-future-of-mmog-development-part-1/">T-Machine</a>. It lays out how entity systems are supposed to work.

Do all these items need to be in separate entities? Could you have a single machine with different components that are added to the machine. Or does each entity have a complex amount of stuff that is attached to it?

The each entity has two identifiers; Entity.Id which is an int and Entity.UniqueId which is a long and is a unique identifier for the Entity in the world.

If you need heavy hierarchy, you may want to keep to Object Oriented Programing. Entity systems are about jamming together lots of components that then make up how the entity behaves. Components should just have data in them depending on what components are attached to an entity, it behaves differently.

You may want to use the EntitySystemProcessors to determine how the machine acts instead. So if I have wheels, a steering wheel and a body, then I act like a plane. If I have wheels, a body, wings, and a joystick, I act as a pilot.

Can you go into more depth about your machine you are building. Is it for a game, is it for a company?

**Comment by KingKnecht** [comment]
Yes, I have read it.
It's not a game. It's an application where the user can put together different configurations of a machine or part of machine. Maybe you can image it like a bill of material.
To be honest, I have no need for the systems and the game-update stuff. But I like the idea of being able to store diverse data in an entity. I could make a entity which represents some sort of a connector, cable, valve, terminal, what ever. E.g. a connector has an article-number, component-code, supplier, a device-designation (consists of assignment, location, name) and many other of such attributes. Some are simple strings, some are more complex. Then there are many types of connectors: Some are sealed, some have configurable insets, some are more like adapters, some have jumpers, some have fuses and so on. In classic OOP this would become a inheritance nightmare. And this is only for simple connectors. 
Next, a connector definitely has pins. Pins are complex entities themselves. Here I need would like to reference from connector to its pins (1:n).

Or take a cable. There is parallel cable, coax cable, normal cable, shielded cable, parallel coax etc.
Here again, a cable has cores (1:n).

Next, let's say the user can configure two connectors from some pre-defined options and rules and a cable. Then the user puts this into an assembly. This assembly then get's an own article-number, and so on.

I hope you get an idea.

**Comment by KellanHiggins** [comment]
Hmmm very interesting!

So you'd like to have each entity represent a part that can be used. Then, you add components to build up an entity into the system it is supposed to represent? So for example, you would have a cable. In the cable, there would be the following components. CableComponent, MaterialComponent, ConnectionComponent.

Cable would signify that this has a cable in it. Material would be the material the cable is made out of. You can define the material within the component. And then Connection component, which would dictate what this cable is connected between. Then you can use these components elsewhere and even use the Connection Component to connect something that isn't a cable.

Does that sound right?

As for systems, how do you intend to modify the data within those components. Entity Components usually don't have methods within them, instead you use the Systems to modify the data. If you want something to happen once, you can use the QueueSystemProcessing processor. You add the entity to the processor and then it automatically updates it in that round. The loop also helps accept input from the UI or however you will display the info.

Anyways, sounds like a good idea. You can easily store references to other entities within a component. I currently store the entity reference of the magazine in my RangedWeaponComponent in my game. I try to avoid this as you can get null issues and the linking up of things usually causes problems down the road.

Hope that helps and sorry if I sounded condescending. Everyone I've talked to in person has no clue what Entity Systems are. I was making sure you had done the required reading :).

**Comment by KingKnecht** [comment]
No problem. It was a good question to make sure I know the basics.
Your picture goes in the right direction, even if I didn't had in mind at that moment that it could be important on which side of the cable is which connector. But hey, I don't know what marketing department asks me to support tomorrow ;-)

At the moment this is my understanding / I think about:
1. It's impossible to have a God-Connector/Cable/Value/Switch/etc. class. OOP inheritance nightmare -> ECS seems to solve this problem.
2. There is a lot of hierarchical relation going on. Not the strength of ECS. I was thinking if it would be handy to have a "Hierarchy-Manager" (or multiple) in the background. Something like the Group-Manager. Then I would ask this manager for relations of my entities instead of having the relations as components. This would be an external management of the relations.  How does this sound to you?
3. I feel like, there is a lack of filter opportunities. Via Aspects I can do things like:

var entities = world.EntityManager.GetEntities(Aspect.All(new[] {typeof (Parent)}));
Where Parent is a component which just holds a ParentId (int)
This would give me all root-assemblies. But I can't ask for parents with specific value. Something like:

var entities = world.EntityManager.GetEntities<Parent>(x => x.ParentId == 12345).

In a system, I think you always want to process all entities which have a Parent component. But in a business application it is often necessary (and enough) the retrieve on particular entity. Like querying a DB.
4. I like the idea to use only IDs for referencing much more than using real references. One reason is, that a list of integers is very simple to serialize when saving project state :-)
5. Maybe it would be possible to add a class named "Reference" which is used like:

Reference Parent {get;set;}

Supposed "Reference" knows "EntityManager" It could help to set an id (int) and get back an entity in its value: Parent.Value. This would omit  code like: 

var p = world.GetEntity(c.GetComponent<Parent>().ParentId); //her I ignore that it could be null.

then I could write:

var p = c.Parent.Value;

But this is fancy stuff ;-)
6. At the moment, playing with the framework, I don't use any system. I just use the world to create and retrieve entities and EntityManager for filtering by aspects. No need for system. I can change all components manually if I like.

I have to sleep now. Maybe I have a better idea what I really need next days. It's hard to focus on the really important things. Thx for reading ;-)

**Comment by KellanHiggins** [comment]
Are you familiar with interfaces? If you don't need all the stuff that Entity Systems can provide, you may be able to get away with your component style system with interfaces.

You could create a new class called CoaxCable and include all the types of components you want included in them. The interfaces demand that you implement whatever is within there interface files.

public class CoaxCable: Part, IMaterial, IConnections, ICable

It won't be as flexible as Entity Systems since you can't add and remove parts at run time. But it will be simpler than learning ES.

Even if you use OOP systems, I think you'll need to implement a part manager anyways. So whether you use ES or OOP, you'll be implementing something.

I feel you are on the right track, so good luck!
