### ISSUE TITLE
RandomSelector misses last behavior always

### ISSUE THREAD

**Issue by Katumies** [thelinuxlich/artemis_CSharp#83]
RandomSelector never selects last behavior.

This is the cause

    switch (_Behaviors[_Random.Next(0, _Behaviors.Length - 1)].Behave())

If _Behaviors length is 4, this turns to (0,3) and because random min, max bounds work stupidly, this means that we are selecting number between 0 and 2, never 3. 

So, in order to fix this, remove the -1

    switch (_Behaviors[_Random.Next(0, _Behaviors.Length)].Behave())

https://msdn.microsoft.com/en-us/library/2dx6wyd4.aspx
>The exclusive upper bound of the random number returned. maxValue must be greater than or equal to minValue.

**Comment by thelinuxlich** [comment]
can you send a PR?

**Comment by Katumies** [comment]
Damn, its time to go sleep. This was not meant for Artemis. Its bug in BehaviorLibrary :) 
Sorry, this can be removed. Too tired..
