### ISSUE TITLE
Tag System

### ISSUE THREAD

**Issue by GrafSeismo** [thelinuxlich/artemis_CSharp#94]
Following scenario:
I have a LevelSystem and a MusicAudioSystem. Both needed to be unique in Usage. I generally would use LevelSystem with base of TagSystem. For each loaded Level i want the Music got started or the song changed, so i also use a TagSystem as base for the MusicAudioSystem. But i am ablte to set only one Tag to an (unique and single) Entity
```c
        /// <summary>Creates the level.</summary>
        /// <param name="entityWorld">The entity world.</param>
        /// <param name="name">The name.</param>
        /// <param name="playerCount">The player count.</param>
        /// <returns>The <see cref="Entity" />.</returns>
        public static void CreateLevel(EntityWorld entityWorld, string name, int playerCount)
        {
            world = entityWorld;
            var entity = world.CreateEntity();
            entity.AddComponent(new Level {Name = name, PlayerCount = playerCount});
            entity.AddComponent(new MusicAudio("Game") { State = EditorSystem.IsActivated ? MusicAudio.StateType.Stop : MusicAudio.StateType.Play });
            entity.Group = "Level";
            entity.Tag = "Level";
            entity.Refresh();
        }
```
I need to configure the MusicAudioSystem with "Level" instead of "MusicAudio". Should not the Tag System better support more then one entity Tag? Is this a design flaw or do i misunderstand anything?

**Comment by thelinuxlich** [comment]
Maybe Tag is a bad name, it was always supposed to work like this, if you need multiple Tags you should do it with Components instead

**Comment by GrafSeismo** [comment]
so maybe we should rethink the supposed way? If i use the default method (with Components) i am not save that another entity exists except of the Tag from one or the other and with the possibility to crash the runtime or result in strange and unwanted behaviors. So there is no other way currently to ensure uniqueness for specific types of entities?

On the other hand it would be in my case just a cosmetique change...well, it was just an idea.
